### ISSUE TITLE
Open in appcenter button in dashboard

### ISSUE THREAD

**Issue by aitor-gomila** [elementary/appcenter-web#90]
### Problem

When browsing the [elementary dashboard](https://appcenter.elementary.io/), when you find an app that you would like to install, you need to copy its ID and install it from the terminal or search it in the app center. Same for flathub.

### Proposal

It would be easier to have a button like `Open in appcenter` that redirects to a protocol like `appcenter://io.elementary.music/5.1.1` that appcenter can handle.

This would NOT install it directly, this would only show the page for the application. This would also allow it to work with regular flatpaks from flathub without it being a very strong security risk.

**Comment by aitor-gomila** [comment]
Then it would be as simple as implementing it in dashboard! Nice

**Comment by aitor-gomila** [comment]
I am getting the following error when trying to `generate-flatpak.rb`

```bash
gitpod /workspace/appcenter-web (main) $ ruby generate-flatpak.rb
generate-flatpak.rb:13:in `initialize': No such file or directory @ rb_sysopen - http://flatpak.elementary.io/repo/appstream/x86_64/appstream.xml.gz (Errno::ENOENT)
        from generate-flatpak.rb:13:in `open'
        from generate-flatpak.rb:13:in `<main>'
```

**Comment by aitor-gomila** [comment]
Fine, working alright now :-)

**Comment by aitor-gomila** [comment]
Where is the template for the application page? Because `generate-flatpak.rb` generates a markdown file, but there is only data in it (and the application description below)

**Comment by aitor-gomila** [comment]
Added PRs #91 and #92, couldn't test it because of an error:
```
<internal:/home/gitpod/.rvm/rubies/ruby-3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- webrick (LoadError)
```

**Comment by aitor-gomila** [comment]
Closing as #91 is merged
